### ISSUE TITLE
Building fails on Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by fabian-thomas** [jackwilsdon/seedvault-extractor#1]
I get the following when building on Ubuntu 20.04.6 LTS:
```
build github.com/jackwilsdon/seedvault-extractor/cmd/extract: cannot load crypto/ecdh: malformed module path "crypto/ecdh": missing dot in first path element
```
I did not find a way to fix this quickly. Maybe you have some idea. `grep -iR ecdh` returns nothing so probably it has to do with a dependency?

On Arch the binary builds fine.

**Comment by jackwilsdon** [comment]
What's the output of `go version` on your system? `seedvault-extractor` needs `crypto/ecdh` which was only added in Go 1.20.

**Comment by jackwilsdon** [comment]
More specifically, we depend on `golang.org/x/crypto` v0.8.0, which depends on `crypto/ecdh`.

**Comment by fabian-thomas** [comment]
`go version go1.13.8 linux/amd64`, so thats the problem.

**Comment by jackwilsdon** [comment]
Yep. You should be able to copy the compiled binary from your Arch machine, as Go binaries are static. I'll add a note to the README indicating the required Go version.
