### ISSUE TITLE
usage: seedvault-extractor-linux-amd64 path-to-backup mnemonic

### ISSUE THREAD

**Issue by jorge-1024** [jackwilsdon/seedvault-extractor#23]
Hi!
Thank you in advance for your help. I'm a regular user. I'm trying to extract my Seedvault's backup, but I encounter the following message: "usage: seedvault-extractor-linux-amd64 path-to-backup mnemonic". I attach a screenshot. I'd appreciate any help in the right direction. I'm using Trisquel GNU which is based in Ubuntu. Thank you very much and congrats for your work!

Jorge.
![Captura de pantalla_2024-04-14_21-05-51](https://github.com/jackwilsdon/seedvault-extractor/assets/166959799/0f5cc47c-5d85-4250-a0b6-fa443a0fcd87)

**Comment by jackwilsdon** [comment]
Did you wrap your mnemonic in quotes? It needs to be passed as a single argument:

```text
$ ./seedvault-extractor .SeedVaultAndroidBackup/1681333934634 "my mneumonic here"
```

**Comment by jorge-1024** [comment]
It worked fine when I put the quotes. Thank You!

**Comment by jackwilsdon** [comment]
Happy to hear!
